server:
  port: 8085
spring:
  config:
    import: "optional:file:./.local/nihongo-staff.properties,optional:file:../.local/nihongo-staff.properties"
  application:
    name: staff-service
  datasource:
    url: jdbc:mysql://onehost-amdcloudhn022602.000nethost.com:3306/tsezwyvdhosting_nihongo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: tsezwyvdhosting_nihongo_app
    password: thuThuy@1
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 45000
      idle-timeout: 30000
      connection-timeout: 30000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

monitoring:
  prometheus-url: ${PROMETHEUS_URL:http://160.22.107.232:9090}
  prometheus-targets-file: /etc/prometheus/targets/node_targets.json
  prometheus-port: 22
  prometheus-host: ${PROMETHEUS_HOST:160.22.107.232}
  prometheus-ssh-username: root
  prometheus-ssh-password: ${MONITORING_PROMETHEUS_SSH_PASSWORD:thanKiemhp@1}

jwt:
  secret: "U7tjRTsx0baZLsRhHGcc0FA/B7MJ65IfQ0jZHvUyYrE="
